---
title: "Untitled"
author: "Eduard Martinez"
date: "8/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 

### 1. Descargue los datos de la GEIH para el mes de junio en el año 2019 y el año 2020 (en formato csv o dta)

Datos de 2019 [aquí](http://microdatos.dane.gov.co/index.php/catalog/599/get_microdata)

Datos de 2020 [aquí](http://microdatos.dane.gov.co/index.php/catalog/659/get_microdata)

### 2. Importe los datos de los ocupados en las Àreas Metorpolitanas -AM- (**Area - Ocupados**) al entorno de R usando las funciones vistas en clase y cree dos objetos llamados ocupados_2019 y ocupados_2020.

### 3. Usando el factor de expancion **fex_c_2011**:

#### 3.1 Calcule el numero de ocupados totales en las AM durante el mes de junio de 2019 y 2020. Pinte sobre la consola la diferencia en el numero de coupados.

#### 3.2 Calcule el numero de ocupados totales para cada AM durante el mes de junio de 2019 y 2020.

#### 3.3 Calcule el salario promedio (```INGLABO```) durante el mes de junio de 2020, para cada AM.

#### 3.4 Repita los puntos ```3.1```, ```3.2``` y ```3.3``` para los usuarios que tienen contrato laboral verbal o escrito (variable ```P6440```).

### 4. Exporte los objetos ocupados_2019 y ocupados_2020 en dos archivos de extencion .rds (los vamos a usar en el proximo ejercicio)



