---
title: Task Clase 2
author: "Eduard F Martinez-Gonzalez"
date: "8/18/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style type="text/css">
h1 {
  font-size: 34px;
  color: red
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
p {
 font-size: 16px;
 color: black
}
li {
 font-size: 16px;
 color: black
}
.table th:not([align]) {
  text-align: left;
}
</style>

# Vectores

* Construya un vector con los numeros pares del 3 a 27.

* Construya un vector con los numeros pares del 4 al 20 en orden descendente. 

* Construya un vector con todas las letras del alfabeto (llamelo a_z).

* Construya un vector con la posicion de las vocales en el vector a_z 

* Se puede crear un vector que contenga letras y numeros? Se altera el tipo de dato?




# Matrices 

* Construya una matriz (llamada matriz_normal) de dimensiones 10x4 con numeros aleatorios de una ditribucion normal con Mean = 10 y SD = 3 .

* Consulte las dimensiones de la matriz

* De matriz_normal extraiga la primera columna y genere un vector (llamado vector_normal).

* Pinte sobre la consola el elemento de la fila 4 y la columna 3 de la matriz




# Dataframes

* Convierta matriz_normal en un dataframe (llamelo data_normal) y verifique que este nuevo objeto es un dataframe.

* Consulte los nombres de las columnas del dataframe y despues asigeneles los siguientes nombres c("col_1","col_2","col_3","col_4")

* Pinte sobre la consola los elementos de la fila 3 del dataframe

# Listas

* Cree una lista vacia (llamela lista_datos)

* Guarde la matriz matriz_normal en la posicion 1 de lista_datos

* Pinte sobre la consola la columna 2 de matriz_normal que esta guardada en lista_datos




